server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
        location = /index.html {
        add_header Cache-Control "no-cache, no-store, must-revalidate";
        }
        # 对静态资源（带哈希）启用长久缓存
        location /assets/ {
            expires 1y;
            add_header Cache-Control "public";
        }
    }

    location /react/ {
        proxy_pass http://fastapi:8000/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}